package com.ensimag.api.message;

import java.io.Serializable;

/**
 * interface that defines a message propagated on the bank network
 * 
 * @author guillaume
 * 
 * @param <ResultType>
 *            the type of the result generated by the embedded action
 */
public interface IMessage<ResultType extends Serializable, NodeType> extends Serializable, Cloneable {

	/**
	 * @return the id of the message
	 */
	long getMessageId();

	/**
	 * @return the action associated to the message
	 */
	IAction<ResultType, NodeType> getAction();

	/**
	 * @return the original bank sender id
	 */
	long getOriginalBankSenderId();

	/**
	 * @return the node sender id for the message
	 */
	long getSenderId();

	/**
	 * @param senderId
	 *            set the sender id for the message
	 */
	void setSenderId(long senderId);

	/**
	 * @return the target bank id for the message
	 */
	long getDestinationBankId();

	/**
	 * @return clone of the message object
	 */
	IMessage<ResultType, NodeType> clone();

	/**
	 * @return the message type
	 */
	EnumMessageType getMessageType();

}
